# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do

  end

# THIS LANE UPLOADS TO TESTFLIGHT LOCALLY
  desc "Push a new beta build to TestFlight Locally"
  lane :beta do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_PRIVATE_KEY'],
      is_key_content_base64: true
    )
    sync_code_signing(
      type: "appstore",
      readonly: true,
      app_identifier: ["dev.scottbennett.GHAT1"],
      # api_key: api_key,
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"])
    )
    # increment_build_number(xcodeproj: "GHAT1.xcodeproj") # Does not keep version in sync between githup and local
    build_app(scheme: "GHAT1")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end


# EXTRA UTILS
  desc "Installs certificate type on system"
  lane :sync_all_development do
    match(type: "development")
  end

  desc "Refresh certificates"
  lane :certificates do
    match(app_identifier: ["dev.scottbennett.GHAT1"])
  end
end
