# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do

    # Check to see if on CI, will hang if not present
    setup_ci if ENV["CI"]

    # Setup Provisioning
    app_store_connect_api_key(
      # key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      # issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      # key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: true
    )

    # Match - Automatically loads Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
    # sync_code_signing
    match(
      type: "appstore",
      readonly: true,
      app_identifier: ["dev.scottbennett.GHAT1"],
      git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_BASIC_AUTHORIZATION"])
    )

    # increment_build_number(xcodeproj: "GHAT1.xcodeproj") # Does not keep version in sync between githup and local
    # add cd "${PROJECT_DIR}" ; agvtool bump to build scheme

    # Builds app
    # build_app
    gym(scheme: "GHAT1")

    # Uploads app to TestFlight
    # upload_to_testflight
    pilot(skip_waiting_for_build_processing: true)
  end


# EXTRA UTILS
  desc "Installs certificate type on system"
  lane :sync_all_development do
    match(type: "development")
  end

  desc "Refresh certificates"
  lane :certificates do
    match(app_identifier: ["dev.scottbennett.GHAT1"])
  end
end
